name: project_nineties
description: "A new Flutter project."

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.4.3 <4.0.0"

dependencies:
  animated_text_kit: ^4.2.2
  badges: ^3.1.2
  barcode_widget: ^2.0.4
  bloc: ^9.0.0
  cloud_firestore: ^5.0.1
  csv: ^6.0.0
  cupertino_icons: ^1.0.6
  dartz: ^0.10.1
  equatable: ^2.0.5
  excel: ^4.0.3
  file_picker: ^8.0.6
  file_saver: ^0.2.13
  firebase_auth: ^5.1.0
  firebase_core: ^3.1.0
  firebase_storage: ^12.0.1
  fl_chart: ^0.68.0
  flow_builder: ^0.1.0
  flutter:
    sdk: flutter
  flutter_bloc: ^9.0.0
  flutter_colorpicker: ^1.1.0
  flutter_facebook_auth: ^7.0.0
  flutter_screenutil: ^5.9.3
  formz: ^0.7.0
  get_it: ^8.0.3
  google_fonts: ^6.2.1
  google_sign_in: ^6.2.1
  http: ^1.2.2
  image_picker: ^1.1.2
  image_picker_web: ^4.0.0
  intl: ^0.20.1
  mobile_scanner: ^6.0.2
  pretty_qr_code: ^3.3.0
  qr_code_scanner: ^1.0.1
  qr_flutter: ^4.1.0
  qrcode_reader_web: ^1.1.1
  rxdart: ^0.28.0
  shared_preferences: ^2.2.3
  sign_in_with_apple: ^6.1.1
  universal_html: ^2.2.4

dev_dependencies:
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/
