name: project_nineties
description: "A new Flutter project."

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.4.3 <4.0.0"

dependencies:
  bloc: ^8.1.4
  cloud_firestore: ^5.0.1
  cupertino_icons: ^1.0.6
  dartz: ^0.10.1
  equatable: ^2.0.5
  firebase_auth: ^5.1.0
  firebase_core: ^3.1.0
  firebase_crashlytics: ^4.0.1
  firebase_storage: ^12.0.1
  flow_builder: ^0.1.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  flutter_facebook_auth: ^7.0.0
  formz: ^0.7.0
  get_it: ^7.7.0
  google_fonts: ^6.2.1
  google_sign_in: ^6.2.1
  image_picker: ^1.1.2
  image_picker_web: ^4.0.0
  path_provider: ^2.1.3
  rxdart: ^0.27.7
  shared_preferences: ^2.2.3
  sign_in_with_apple: ^6.1.1
  universal_html: ^2.2.4

dev_dependencies:
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/
